service: <name>

plugins:
  - serverless-step-functions

provider:
  name: aws                 # Currently, only aws is supported
  runtime: nodejs[10|12].x  # Currently, only nodejs is supported
  environment:
    WATCHTOWER_EVENT_KINESIS_STREAM:
      Ref: EventsStream
    # DEBUG_WATCHTOWER: 1    # Produces verbose debug prints
    # PROFILE_WATCHTOWER: 1  # Produces timing information
  iamRoleStatements:
    - Effect: Allow             # Required for writing wt events
      Action:
        - 'kinesis:DescribeStream'
        - 'kinesis:PutRecord'
        - 'kinesis:PutRecords'
      Resource:
        Fn::GetAtt: [EventsStream, Arn]

functions:
  watchtower-ingestion: ${file(watchtower/functions.yml):watchtower-ingestion}   # Event ingestion function
  watchtower-monitor:   ${file(watchtower/functions.yml):watchtower-monitor}     # Event monitor
  wt-monitor-trigger:   ${file(watchtower/functions.yml):wt-monitor-trigger}     # A function that triggers the event monitoring step-functions state machine

resources:
  Resources:
    EventsTable:          ${file(watchtower/ddbTables.yml):Resources.EventsTable}
    CheckpointsTable:     ${file(watchtower/ddbTables.yml):Resources.CheckpointsTable}
    InvocationStream:     ${file(watchtower/kinesisStreams.yml):Resources.InvocationStream}
    EventsStream:         ${file(watchtower/kinesisStreams.yml):Resources.EventsStream}
    EventWriterRole:      ${file(watchtower/iamRoles.yml):Resources.EventWriterRole}
    EventReaderRole:      ${file(watchtower/iamRoles.yml):Resources.EventReaderRole}
    StateMachineListExec: ${file(watchtower/iamRoles.yml):Resources.StateMachineListExec}
  Outputs:
    WTCheckerMachine: ${file(watchtower/outputs.yml):Outputs.WTCheckerMachine}

custom:
  # handlerFilePostfix: '-wrapper'
  # handlerFilePostfix: ''
  handlerFilePostfix: ${env:WT_RUN_NO_RECORDING, '-wrapper'}

stepFunctions:
  stateMachines:
    checker: ${file(watchtower/stateMachine.yml):stateMachines.checker}
