service: <name>

plugins:
  - serverless-step-functions

provider:
  name: aws                 # Currently, only aws is supported
  runtime: nodejs[10|12].x  # Currently, only nodejs is supported
  environment:
    WATCHTOWER_EVENT_KINESIS_STREAM:
      Ref: EventsStream
      # Fn::ImportValue: watchtower-events-kinesis-stream   # When deploying multiple separate stacks

    # DEBUG_WATCHTOWER: 1    # Produces verbose debug prints
    # PROFILE_WATCHTOWER: 1  # Produces timing information
  iamRoleStatements:
    - Effect: Allow             # Required for writing wt events
      Action:
        - 'kinesis:DescribeStream'
        - 'kinesis:PutRecord'
        - 'kinesis:PutRecords'
      Resource:
        Fn::GetAtt: [EventsStream, Arn]
        # Fn::ImportValue: watchtower-events-kinesis-stream-arn   # When deploying multiple separate stacks

functions:
  watchtower-ingestion: ${file(${self:custom.wtPathPrefix}watchtower/functions.yml):watchtower-ingestion}   # Event ingestion function
  watchtower-monitor:   ${file(${self:custom.wtPathPrefix}watchtower/functions.yml):watchtower-monitor}     # Event monitor
  wt-monitor-trigger:   ${file(${self:custom.wtPathPrefix}watchtower/functions.yml):wt-monitor-trigger}     # A function that triggers the event monitoring step-functions state machine

resources:
  Resources:
    EventsTable:          ${file(${self:custom.wtPathPrefix}watchtower/ddbTables.yml):Resources.EventsTable}
    CheckpointsTable:     ${file(${self:custom.wtPathPrefix}watchtower/ddbTables.yml):Resources.CheckpointsTable}
    InvocationStream:     ${file(${self:custom.wtPathPrefix}watchtower/kinesisStreams.yml):Resources.InvocationStream}
    EventsStream:         ${file(${self:custom.wtPathPrefix}watchtower/kinesisStreams.yml):Resources.EventsStream}
    EventWriterRole:      ${file(${self:custom.wtPathPrefix}watchtower/iamRoles.yml):Resources.EventWriterRole}
    EventReaderRole:      ${file(${self:custom.wtPathPrefix}watchtower/iamRoles.yml):Resources.EventReaderRole}
    StateMachineListExec: ${file(${self:custom.wtPathPrefix}watchtower/iamRoles.yml):Resources.StateMachineListExec}
  Outputs:
    WTCheckerMachine: ${file(${self:custom.wtPathPrefix}watchtower/outputs.yml):Outputs.WTCheckerMachine}
    WTEventsKinesisStream: ${file(${self:custom.wtPathPrefix}watchtower/outputs.yml):Outputs.WTEventsKinesisStream}
    WTEventsKinesisStreamARN: ${file(${self:custom.wtPathPrefix}watchtower/outputs.yml):Outputs.WTEventsKinesisStreamARN}


custom:
  # handlerFilePostfix: '-wrapper'
  # handlerFilePostfix: ''
  handlerFilePostfix: ${env:WT_RUN_NO_RECORDING, '-wrapper'}
  wtPathPrefix: "src/"

stepFunctions:
  stateMachines:
    checker: ${file(${self:custom.wtPathPrefix}watchtower/stateMachine.yml):stateMachines.checker}
