service: feature-extraction

custom: ${file(../custom.yml)}

provider:
  name: aws
  runtime: nodejs8.10
  deploymentBucket: ${self:custom.deploymentBucket}
  stage: ${self:custom.stage}
  profile: ${self:custom.profile}
  region: ${self:custom.region}


functions:
  extractFeatures:
    handler: handler.handler

    events:
      - http:
          path: users/create
          method: get
    role:
      'Fn::GetAtt': [ S3ImageRekognitionRole, Arn ]

resources:
  Resources:
    # Roles
    S3ImageRekognitionRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: S3ImageRekognitionRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
        ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

        Policies:
        - PolicyName: StoreImageLabelsInBucket
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - 's3:putObject'
              Resource: arn:aws:s3:::rnrtempbucket/*
        - PolicyName: ReadImageFromBucket
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - 's3:putObject'
              Resource: arn:aws:s3:::rnrtempbucket/*
        - PolicyName: RunRekognition
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - 'rekognition:*'
              Resource: '*'

  Outputs:
    FeatureExtractionName:
      Description: The Name of the Feature Extraction Lambda
      Value:
        Ref: ExtractFeaturesLambdaFunction
      Export:
        Name: FeatureExtractionLambdaFunctionName
    FeatureExtractionArn:
      Description: The Arn of the Feature Extraction Lambda
      Value:
        'Fn::GetAtt': [ ExtractFeaturesLambdaFunction, Arn ]
      Export:
        Name: FeatureExtractionLambdaFunctionArn