service: lorem-writer-reader

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  environment:
    LOREM_DYNAMO_TABLE:
      Ref: LoremTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        Fn::GetAtt: [LoremTable, Arn]

package:
  exclude:
    - '*~'

functions:
  produce:
    handler: handler.produce
    events:
      - http:
          path: lorem/produce
          method: get

  consume:
    handler: handler.consume
    events:
      - http:
          path: lorem/consume
          method: get

resources:
  Resources:
    LoremTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: digest
          AttributeType: S
        KeySchema:
        - AttributeName: digest
          KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-${self:provider.stage}-LoremTable
