service: retro-example-dep

plugins:
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  region: eu-west-2
  stage: dev
  environment:
    WATCHTOWER_EVENT_KINESIS_STREAM:
      Ref: EventsStream
    DEBUG_WATCHTOWER: 1
    # PROFILE_WATCHTOWER: 1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'kinesis:DescribeStream'
        - 'kinesis:PutRecord'
        - 'kinesis:PutRecords'
      Resource:
        Fn::GetAtt: [EventsStream, Arn]

functions:
  watchtower-ingestion: ${file(watchtower/functions.yml):watchtower-ingestion}
  watchtower-monitor: ${file(watchtower/functions.yml):watchtower-monitor}
  wt-monitor-trigger: ${file(watchtower/functions.yml):wt-monitor-trigger}

resources:
  Resources:
    EventsTable: ${file(watchtower/ddbTables.yml):Resources.EventsTable}
    CheckpointsTable: ${file(watchtower/ddbTables.yml):Resources.CheckpointsTable}
    InvocationStream: ${file(watchtower/kinesisStreams.yml):Resources.InvocationStream}
    EventsStream: ${file(watchtower/kinesisStreams.yml):Resources.EventsStream}
    EventWriterRole: ${file(watchtower/iamRoles.yml):Resources.EventWriterRole}
    EventReaderRole: ${file(watchtower/iamRoles.yml):Resources.EventReaderRole}
    StateMachineListExec: ${file(watchtower/iamRoles.yml):Resources.StateMachineListExec}
  Outputs:
    WTCheckerMachine: ${file(watchtower/outputs.yml):Outputs.WTCheckerMachine}

custom:
  # handlerFilePostfix: '-wrapper'
  # handlerFilePostfix: ''
  handlerFilePostfix: ${env:WT_RUN_NO_RECORDING, '-wrapper'}

stepFunctions:
  stateMachines:
    checker: ${file(watchtower/stateMachine.yml):stateMachines.checker}
