service: image-get-and-process-step-function

custom: ${file(../shared.yml)}

provider:
  name: aws
  runtime: nodejs8.10
  deploymentBucket: ${self:custom.deploymentBucket}
  profile: ${self:custom.profile}
  region: ${self:custom.region}
  stage: ${self:custom.stage}

resources:
  Resources:
    # Role
    StepFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: ${self:custom.stage}RandomPhotoFeaturesStepFunction
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: states.${self:custom.region}.amazonaws.com
        ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
        Policies:
        - PolicyName: InvokeLambdas
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - 'lambda:InvokeFunction'
              Resource:
              - 'Fn::ImportValue': FeatureExtractionLambdaFunctionArn
              - 'Fn::ImportValue': RandomImageFetchLambdaFunctionArn
    # Step Function
    StepFunction:
      Type: 'AWS::StepFunctions::StateMachine'
      Properties:
        DefinitionString: '${file(features.js):shim}'
        RoleArn:
          'Fn::GetAtt': [ StepFunctionRole, Arn ]
